# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_left
    - joint_right
    - left_front_joint
    - left_rear_joint
    - right_front_joint
    - right_rear_joint
  sim_control_mode: 1  # 0: position, 1: velocity
controller_list:
  []
rover_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6


rover_arm_right_finger:
    type: position_controllers/JointPositionController
    joint: joint_right


rover_arm_left_finger:
    type: position_controllers/JointPositionController
    joint: joint_left
